### ISSUE TITLE
css隔离

### ISSUE THREAD

**Issue by wineSu** [ctripcorp/wepack#10]
打包后，子组件的样式会影响到父组件，目前没有做一个很好的css隔离。

**Comment by yisar** [comment]
要想解决这个问题，只能遍历 css 的 ast，然后把 css 类名给重命名一遍了

svelte 中做了这个工作，可我咋感觉工作量比较大

https://www.github.com/sveltejs/svelte/tree/master/src%2Fcompiler%2Fcompile%2Fcss%2FSelector.ts

vue 是咋做的

**Comment by yisar** [comment]
使用 vue 的方案

https://github.com/vuejs/vue-loader/blob/v14.2.2/lib/style-compiler/plugins/scope-id.js

input

```html
<style>
    .example{
        color:red;
    }
</style>

<div>scoped</div>
```
output

```html
.example[data-scoped-5558831a] {
  color: red;
}

 <div class="example" data-scoped-5558831a>scoped</div>

```

**Comment by yisar** [comment]
暂时搞定了 class 级别的 https://github.com/ctripcorp/wepack/pull/12
