### ISSUE TITLE
找不到命令：create-wepack

### ISSUE THREAD

**Issue by anyexinglu** [ctripcorp/wepack#23]

**Comment by anyexinglu** [comment]
![image](https://user-images.githubusercontent.com/8243326/111245137-1f3bb380-863f-11eb-914f-b16db027524d.png)

**Comment by anyexinglu** [comment]
yarn 改成 npm i 也一样

**Comment by yisar** [comment]
暂时还没发包
https://github.com/ctripcorp/wepack/discussions/15
可以先这么调试

**Comment by anyexinglu** [comment]
> 暂时还没发包
> #15
> 可以先这么调试

这样是可以，另外启动其他问题记录在这里了：https://github.com/anyexinglu/wepack/commit/aef3b2f71d845354e6771db811fd6cf7429c6d87#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R23-R33

**Comment by yisar** [comment]
@anyexinglu 可以提一下 pr，wepack 名字只是暂定，我还在取名字呜呜呜

**Comment by anyexinglu** [comment]
> @anyexinglu 可以提一下 pr，wepack 名字只是暂定，我还在取名字呜呜呜

嗯，上面的操作步骤只是能在小程序工具跑起来，不一定合理。等我看明白你的代码再说 😂

**Comment by yisar** [comment]
> 嗯，上面的操作步骤只是能在小程序工具跑起来，不一定合理。等我看明白你的代码再说 😂

hash 那个可以提的，直接在线编辑就可以了，方便快捷
